### ISSUE TITLE
Warning and Errror on CI related to lattice tools and hypothesis

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#261]
On one a build for #260, there was an warning and error (https://travis-ci.org/simphony/simphony-common/builds/101036558#L363):  
```
/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/hypothesis/core.py:581: FailedHealthCheck: Your test used the global random module. This is unlikely to work correctly. You should consider using the randoms() strategy from hypothesis.strategies instead. Alternatively, you can use the random_module() strategy to explicitly seed the random module.
See http://hypothesis.readthedocs.org/en/latest/healthchecks.html for more information about this.
warnings.warn(FailedHealthCheck(message))

ERROR: test_changing_tolerance_guess_primitive_vectors (simphony.tools.tests.test_lattice_tools.TestLatticeTools)

----------------------------------------------------------------------
Traceback (most recent call last):

File "simphony/tools/tests/test_lattice_tools.py", line 564, in test_changing_tolerance_guess_primitive_vectors
lattice_tools.guess_primitive_vectors(points, tolerance)
File "simphony/tools/lattice_tools.py", line 162, in guess_primitive_vectors
raise IndexError(message)
IndexError: Failed to deduce the lattice dimensions
```

I reran the travis build an only the warning occurred::
https://travis-ci.org/simphony/simphony-common/builds/101036558#L337

**Comment by nathanfranklin** [comment]
@kitchoi , can you take a look at this.

**Comment by kitchoi** [comment]
@nathanfranklin Thanks for reporting this.
I don't think the warning is related to the error.  While I cannot reproduce the error, I believe the error is caused by lattice node coordinates deviating too far from the defined numerical precision.  Therefore it is appropriate to get an Error.  However, in this case a ValueError would be more appropriate than an IndexError.  I will change this and edit the error message accordingly.

**Comment by nathanfranklin** [comment]
@kitchoi , thanks!
