### ISSUE TITLE
Add an abstract interface for the Lattice container

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#39]

**Comment by itziakos** [comment]
@tuopuu we need an abstract definition of the class similar to the mesh and particile containers

**Comment by kemattil** [comment]
This was left open by intention (originally it was not considered necessary). However, during our last teleconference with Adham & Nathan, we decided to implement it. It is still in the list of things to do. :)

**Comment by itziakos** [comment]
Please note that this is a high priority item for me since an abstract class with appropriate documentation will provide me with the template for verifying conformance the api of the different engine implementations.

**Comment by kemattil** [comment]
@tuopuu , do you have time this week? Alternatively, I will do it at the beginning of next week (at the latest). The variable node.id should be renamed to node.index in this update.

**Comment by tuopuu** [comment]
Yes, I have time for this, but I have been thinking would it be easier just to add "file=None" optional, last, parameter to abstract Lattice class constructor, so that it would also specify the FileLattice class? To my understanding FileLattice should be an implementation of Lattice class in a Cuds-file. All the other methods in the abstract Lattice are the same in FileLattice. What's your opinion on this, @kemattil and @itziakos?

**Comment by kemattil** [comment]
In my opinion, the "file=None" should be a parameter for the FileLattice class constructor only, i.e. not for the ABCLattice constructor. The constructor of a derived/inherited class can have more parameters than the base class.

**Comment by itziakos** [comment]
implemented in #45
